### ISSUE TITLE
dinghy shouldn't convert to lowercase the URLs

### ISSUE THREAD

**Issue by clopez** [aperezdc/dinghy#4]
Commit a3d726f408c511d02f23372b8cf05d50eb34d819 broke URL loading when the URL contains uppercase letters.

When I try to open https://people.igalia.com/clopez/webBenchmarks/JetStream/JetStream-1.1/index.html with dinghy it tries to open https://people.igalia.com/clopez/webbenchmarks/jetstream/jetstream-1.1/index.html (everything lowercase), which fails with 404 as expected-

**Comment by aperezdc** [comment]
Indeed the problem was introduced in https://github.com/aperezdc/dinghy/commit/a3d726f408c511d02f23372b8cf05d50eb34d819 as you have found out. The string is lowercased to check for the `http://` and `https://` prefixes always in lowercase and the lowercase string should have been used only for that. I'll make a fix for this.
